### ISSUE TITLE
allow prefixes for options

### ISSUE THREAD

**Issue by bueler** [pism/pism#175] opened 2013-09-18 01:13 UTC
I did not want this _suggestion_ to get lost.

Note that PETSc options allow prefixes as in the PetscOptionsPrefixPush(), PetscOptionsPrefixPop() pair and with PetscOptionsBegin().

The correspondence below is from an email from Jed Brown to Robert Fischer on June 21 2013.

```
> ... I mean the PETSc options database.  There may be other global variables that I'm
> not aware of, most likely something related to MPI.  But the PETSc options database is
> what I know is causing problems right now, so that's what I'm focused on.

Are you trying to combine multiple PETSc-using codes?  If so, just ensure that PetscInitialize()
is only called once.

If you've done that, then the issue is probably that you haven't set a prefix.  The second argument
to PetscOptionsBegin is a prefix, and all options accepted in the block are underneath this prefix.
We need this all the time when configuring solvers in PETSc because we create new levels of
nesting and composition at run-time.

> ...
> Unfortunately, I don't think it would.  The problem is, I need to instantiate IceModel and IceGrid
> twice, with two different sets of parameters.  But those parameters come from the PETSc options
> database, and there is just one such database.

A classic use case for different prefixes.  All PETSc objects respect prefixes
(KSPSetOptionsPrefix, etc).  I recommend: add a setOptionsPrefix() method to all PISM
objects.  Then use that prefix in all PetscOptionsBegin(). Your options files can look like

-greenland_opt1 -greenland_opt2 -antarctica_ksp_type gmres

or like

-prefix_push greenland_
  -opt1 -opt2
-prefix_pop
-prefix_push antarctica_
  -ksp_type gmres
-prefix_pop

Note that you can use -options_file inside a -prefix_push block, to reuse your existing files
without modification.
```

**Comment by ckhroulev** [comment] 2021-02-01 22:14
Essentially a duplicate of #176.

**Closed by ckhroulev** 2021-02-01 22:14 UTC
