### ISSUE TITLE
sub_shelf_ice_flux can be nonzero even when iareaf is zero

### ISSUE THREAD

**Issue by bueler** [pism/pism#74] opened 2012-07-04 19:01 UTC
The issue may be worth fixing or it may just need brief documentation.

The symptom is to see time-series `sub_shelf_ice_flux` to be nonzero when either `-float_kill` was used or when a run with another calving model (e.g. `-ocean_kill` in case reported by Antje F.) actually gives no ice.

The cause of the issue (=title) is the order of the calving and sub-shelf mass balance accounting code in `IceModel::massContExplicitStep()`:

``` c++
          if (shelfbmassflux(i, j) < 0 || there_is_ice_due_to_flow)
            my_sub_shelf_ice_flux -= shelfbmassflux(i, j); // note the "-="

      ...

      if ( floating_ice_killed && mask.ocean(i, j) ) {
        my_float_kill_flux -= vHnew(i, j);
        vHnew(i, j) = 0.0;
      }
```

Because of this order, during the time step there can be a bit of floating ice, and we report subshelf melt.

Fixing this may be as simple as reversing order of the above, but I'm afraid it needs thought about other consequences.

**Comment by ckhroulev** [comment] 2017-11-30 17:19
This is fixed in the `dev` branch, but the fix is too involved (and the issue is too minor) to merge it into `master`.

**Closed by ckhroulev** 2017-11-30 17:19 UTC
