### ISSUE TITLE
initMIP Antarctica variable hfgeoubed not constant over time

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#392] opened 2017-09-04 09:50 UTC
initMIP Antarctica experiments requests the constant-in-time 2D-variable `hfgeoubed` (upward_geothermal_heat_flux_at_ground_level), see [wiki](http://www.climate-cryosphere.org/wiki/index.php?title=InitMIP-Antarctica). While in the stable0.7 version (see contribution by @tkleiner [here](http://www.pik-potsdam.de/~albrecht/pism_hfgeoubed/hfgeoubed_AIS_AWI_PISM1Pal_ctrl.nc)) this field seems to coincide widely with the `bheatflx` input field. However, dev version shows some time-varying deviations in the outer grounded ice-sheet regions, in some grid points with negative values, see last out in [jupyther script](https://nbviewer.jupyter.org/url/www.pik-potsdam.de/~mengel/notebooks/check_initmip_data_before_upload.ipynb) or compare with netCDF file [here](http://www.pik-potsdam.de/~albrecht/pism_hfgeoubed/hfgeoubed_AIS_AWI_PISM1Pal_ctrl.nc). I guess this could be a bug, or could this make physical sense? hfgeoubed is a copy of the variable `m_top_surface_flux` in base/energy/BTU_Full.cc. 
Here's an example for reproduction based on the seaRISE experiment: 
`bin/pismr -i examples/searise-antarctica/pism_Antarctica_5km.nc -bootstrap -Mx 381 -My 381 -Lz 6000 -Lbz 2000 -Mz 81 -Mbz 21 -atmosphere given -surface simple -ocean pik -bed_def none -hydrology null -calving eigen_calving,thickness_calving,ocean_kill -eigen_calving_K 2.0e17 -thickness_calving_threshold 140.0 -ocean_kill_file examples/searise-antarctica/pism_Antarctica_5km.nc -ys -5 -ye 100 -options_left -verbose 2 -o_order zyx -backup_interval 3.0 -sia_e 2.0 -ssa_e 0.6 -ssa_method fd -stress_balance ssa+sia -pik -pseudo_plastic -pseudo_plastic_q 0.75 -pseudo_plastic_uthreshold 100.0 -till_effective_fraction_overburden 0.04 -subgl -extra_file extra.nc -extra_times -5:5:105 -extra_vars mask,thk,usurf,topg,bheatflx,heat_flux_from_bedrock,hfgeoubed,velbase,wvelbase,tempbase -o result.nc -o_size big`

**Comment by ckhroulev** [comment] 2017-09-04 17:26
Torsten,

This is a feature and not a bug.

The PISM command you included selects a non-zero-thickness vertical grid in the bedrock thermal layer (`-Lbz 2000 ... -Mbz 21`), so the *upward geothermal flux **at ground level*** is the flux from the bedrock thermal layer into the ice. In other words, you asked PISM to model time-dependent bedrock temperature and you got the corresponding time-dependent heat flux at ground level.

Use `-Mbz 1` to get time-independent heat flux at ground level (which will then be the same as the input field `bheatflx`).

Please let me know if this helps.

PS: Why does InitMIP request `hfgeoubed ` as an output variable If it should be time-independent and equal to the input field `bheatflx`? This does not make sense to me.

**Comment by ckhroulev** [comment] 2017-09-04 18:32
Regarding negative values: an area of bedrock exposed to air can cool down to fairly low temperatures. Now if ice advances to cover this area the ice could easily be warmer than the bed below it, leading to the flow of heat from the ice into the bedrock.

**Comment by talbrecht** [comment] 2017-09-07 17:18
Thanks @ckhroulev for this explanation, this helps, yes. I asked Helene Seroussi about the 'C'-type in the requested variable list in the [wiki](http://www.climate-cryosphere.org/wiki/index.php?title=InitMIP-Antarctica). Helene answered: "In initMIP, we ask people to use a constant geothermal heat flux in order to reduce the number of processes that could impact the results, as the main goal of this preliminary experiment is to understand the impact of initial conditions. I am sorry if there has been some misunderstanding." So I guess we can close this issue?!

**Comment by ckhroulev** [comment] 2017-10-19 00:53
> ... we ask people to use a constant geothermal heat flux in order to reduce the number of processes that could impact the results...

This can be interpreted as asking contributors **not** to use the bedrock thermal layer model (i.e. asking you to use `-Mbz 1`).

I agree, I think we can close this issue.

**Closed by ckhroulev** 2017-10-19 00:53 UTC
