### ISSUE TITLE
Global Variables in Constructors

### ISSUE THREAD

**Issue by citibeth** [pism/pism#190] opened 2013-10-22 13:37 UTC
Constructors of a number of key PISM classes (IceGrid, IceModel, etc) rely on the values of global variables for their construction: through the "NCConfigVariable &conf" parameter.  Although it doesn't LOOK like this is the case, examination of NCConfigVariable reveals that many calls that "look" local actually go to the (global) PETSC options database to get their value.

The result of this is that it becomes difficult to instantiate individual PISM classes outside of the standard runtime framework assumed by existing PISM driver programs.  Configuration and "business logic" are intertwined in an inflexible manner.

In general... references to global variables from within constructors are also unintuitive, and they defeat the purpose of encapsulation.

**Comment by ckhroulev** [comment] 2021-02-01 22:13
Essentially a duplicate of #176.

**Closed by ckhroulev** 2021-02-01 22:13 UTC
