### ISSUE TITLE
create new time-series to report subglacial hydrology model boundary fluxes (to show conservation)

### ISSUE THREAD

**Issue by bueler** [pism/pism#177] opened 2013-09-23 00:43 UTC
The combined amount tillwat+bwat is a conserved quantity of the subglacial hydrology model.  For there to be user-verifiable conservation the fluxes at the boundary must be reported.

At this point the -hydrology routing and -hydrology distributed models give reports to stdout on the amount of water lost at the boundary, for example

```
 'routing' hydrology summary:
     102 hydrology sub-steps with average dt = 0.000027 years = 847.06 s
        (last max |V| = 2.08e-01 m s-1; last max D = 2.65e+00 m^2 s-1)
     ice free land lost = 2.359e+08 kg, ocean lost = 1.980e+08 kg
     negative bmelt gain = 0.000e+00 kg, null strip lost = 4.190e+02 kg
```

This report at stdout is generated in PISMRoutingHydrology.cc, PISMDistributedHydrology.cc.

The quantities "ice free land lost", "ocean lost", "null strip lost" all need time series so that the user can check that the books are balanced.  Quantity "negative bmelt gain" is an error that needs to go to zero under grid refinement, but again it needs a time-series so the user can see this.

**Comment by ckhroulev** [comment] 2016-12-08 00:44
Issue #256 is a duplicate of this one.

**Closed by ckhroulev** 2016-12-08 00:44 UTC
Labels: task
