### ISSUE TITLE
wvelsurf is buggy (most likely an interpolation artifact)

### ISSUE THREAD

**Issue by florianziemen** [pism/pism#328] opened 2015-09-09 12:59 UTC
Hi!

I ran the eisIIA test at high resolution
```
mpirun -n 4 pisms -eisII A -i eisIIA.nc -Mx 411 -My 411 -Mz 50 -Lz 5000 -y 5e4 -o eisIIA_2.nc -extra_file eisIIa-ex -extra_times 1000 -extra_vars thk,velsurf_mag,wvelsurf,rank,wvel,wvel_rel,uvel,vvel -extra_split -ts_file eisIIa-ts.nc -ts_times 1 -o_size big
```

and got fringe patterns in the vertical velocity at the surface after about 3000 years (look along x or y direction, or just look at the plot).  Inside the ice everything looks fine.

<img width="982" alt="wvelsurf" src="https://cloud.githubusercontent.com/assets/6372493/9762107/70bfd6a0-5701-11e5-9ec1-9283e9433f22.png">

I think, this stems from the interpolation using

```c++
/! Copies the values of an IceModelVec3 at the ice surface (specified by the level myH) to an IceModelVec2S gsurf.
void IceModelVec3::getSurfaceValues(IceModelVec2S &surface_values,
                                    const IceModelVec2S &H) const {
```
which calls
```
//! Return value of scalar quantity at level z (m) above base of ice (by linear interpolation).
double IceModelVec3D::getValZ(int i, int j, double z) const {
```
depending on how close we are to the next higher vertical level, more or less of that level's zero velocity gets sucked into the wvelsurf computation (assuming that velocity actually is zero). In some situations I got nice zig-zag patterns alternating between zero vertical velocity and some substantially higher values. Probably one zig-zag per vertical level I was crossing.

Cheers

Flo

**Comment by ckhroulev** [comment] 2015-09-09 16:19
This is definitely a bug and should be fixed.

> ... most likely an interpolation artifact...

I agree with this assessment. Another way to describe this is "`wvelsurf` is sensitive to the value used for `wvel` above the surface of the ice."

Now the question is this: should `PSB_wvel::compute()` [set `wvel` to zero above the ice](https://github.com/pism/pism/blob/stable0.7/src/base/stressbalance/PISMStressBalance_diagnostics.cc#L529), or is it better to use the value at the top of the column *within* the ice?

**Comment by florianziemen** [comment] 2015-09-09 16:39
Good question. I can see good reasons for both options, and don't really have an opinion.
It might be nice to set it to the top value inside the model (so one gets a reasonable number when interpolating for various reasons) and set it to missval when writing output (but that probably is a big, big mess, too).

**Comment by ckhroulev** [comment] 2015-09-09 16:57
Right. We do treat `wvel` differently depending on whether it is [computed for reporting](https://github.com/pism/pism/blob/stable0.7/src/base/stressbalance/PISMStressBalance_diagnostics.cc#L464) or [for other needs](https://github.com/pism/pism/blob/stable0.7/src/base/stressbalance/PISMStressBalance.cc#L192).

The vertical velocity used by the energy model (and elsewhere in PISM) is computed using incompressibility and the basal melt rate and is *extrapolated above the ice*. (See $\tilde w$ in [the source code browser](http://www.pism-docs.org/doxy/html/vertchange.html).)

The *diagnostic* vertical velocity is the *vertical velocity relative to the geoid*, i.e. it includes basal uplift and the influence of the bed slope and is *set to zero above the ice*.

**Comment by bueler** [comment] 2015-09-09 18:55
I do not doubt that the interpolation of `wvelsurf` can be improved.  But @ckhroulev can't do magic here.

That is, nobody should expect much niceness from `wvelsurf` because of the irregularity and sensitivity of the underlying continuum field, i.e. the surface value of the vertical component of the continuum velocity field.  In particular, because of the incompressibility of ice,

>One sees that the vertical velocity is affected by both the first and second derivatives of the surface h, by the divergence of U_b and by the gradient of b.

(page 510 of Bueler et al, 2007. "Exact solutions to the thermomechanically-coupled ...", J. Glaciol. 53 (182)).  The point of this quote is to emphasize that a _second_ derivative of a quantity appears, and _first_ derivatives of others.  These derivatives have no regularity to speak of because the quantities essentially have linear/bilinear representations.  (I.e. if we regard our FD formulas as FEM formulas then they use Q^1 elements for h and b and the velocity.)

Specifically, the surface h, especially if there is bed roughness and/or basal slipperyness irregularities, is a minimally-low-pass-filtered version of basal information.  Thus if we want `wvelsurf` then we want a second derivative of this not-very-nice field.

The issue is not new, battles have been fought before, nobody compares to data because the data is hard to get and terribly noisy because of the above issues, and in fact the PISM output `wvelsurf` is perhaps not worth reporting.

@florianziemen  Do you really want `wvelsurf`?

**Comment by florianziemen** [comment] 2015-09-10 09:38
Hi Ed!
Well, I know `wvelsurf` is a messy story in terrain, but this is a no-terrain case where there is a simple bug.
I think, what I'm much more interested in when analyzing model output is Div Q (`flux_divergence` in pism). I just happened to have the variable in an output file, look into it and then worry about what's happening inside the model. Div Q actually is important because it is the vertical velocity for the temperature advection inside the model... 

As a diagnostic, it needs to be either fixed or removed. I don't know if anybody is using it for anything useful, so I can't say which one is better. I'm fine with removing it. I guessed it's meaning wrong anyways.

Cheers
Flo

**Comment by bueler** [comment] 2015-09-10 16:54
Flo --

You are missing my point.  The 2007 paper is about EISMINT II exactly, on a flat bed, and I quoted the paper because of that context.

The surface elevation `h` in _all existing SIA flat bed models_ is approximated from a piecewise-linear (-bilinear) space.  Thus the second derivative of it is not even close to continuous; technically it would be a bunch of delta functions along all grid edges.  It is this function which is being interpolated when we report `wvelsurf`, and Div Q too, because in the SIA these quantities are functions of (proportional to) the second derivative of `h`.

The general idea in numerical PDEs, e.g. even for the Poisson equation, is that the solution itself can be well-approximated and the numerical approximations can converge at some desired rate (e.g. `O(dx^2)` or such).  However, except in spectral methods, the higher derivatives of the (good) approximation to the solution are bad, and do not converge to the higher derivatives of the continuum solution.

So:  Do you want `wvelsurf` or Div Q or would it be acceptable to have averages, e.g. spatial integrals, of these quantities?  Because the spatial integrals are better.

Ed

**Comment by mccarthyak** [comment] 2015-09-10 16:59
I use flux_divergence to assess how the shock at the beginning of a
relaxation run dissipates.

**Comment by florianziemen** [comment] 2015-09-11 09:22
I think, I want to keep Div Q. It's a pretty good indicator of what's happening in the model (in the end, this is the vertical velocity used in the temperature solver, so it better be not too bad).
When it comes to the simulations we are planning, the integral of Div Q has to be zero (or we have to find a different way to redistribute this value, either as runoff, or as snowfall). Otherwise the numerics are creating/destroying ice. In my PhD, we switched to a pure upwinding surface evolution scheme to accomplish this. I'll look into what's happening in the current code one of the next days.

**Comment by ckhroulev** [comment] 2015-09-11 15:22
> In my PhD, we switched to a pure upwinding surface evolution scheme to accomplish this.

I've been thinking about isolating (modularizing) the 2D mass transport code in PISM for a while now, and this is a good reason to get back to it. If you're willing, I think we should implement a finite-volume-style scheme *in addition* to the current one --- instead of just modifying the code we have now. What do you think?

**Comment by florianziemen** [comment] 2015-09-11 15:32
Hi Constantine!

Might be a good idea, but I’m not sure. 
I tend to want to keep the 2D mass transport consistent with the 3D temperature/enthalpy transport. If I remember correctly, that was quite essential for not getting zebra stripe basal-freeze-on patterns (might also break down to one of the other changes I implemented in the end, but I had them for quite a while). Then this is actually a set of rather large changes so deep in the code that you might *achieve* substantial slowdown by modularizing them, although I’m not sure if that really is the case.

I totally don’t mind the effort involved in a *proper* solution. I just want to avoid unnecessary trouble.

What do you think?

Cheers

Flo

**Comment by ckhroulev** [comment] 2015-09-11 16:23
Hi Flo!

Now that I look at it, the scheme we have [can be thought of as a FV scheme already](https://github.com/pism/pism/blob/stable0.7/src/base/iMgeometry.cc#L634): divQ is computed using cell interface fluxes. (This may not be what you want, of course.) We know that this is mass-conservative in the flat bed case, but not necessarily so when the bed is rough.

> I tend to want to keep the 2D mass transport consistent with the 3D temperature/enthalpy transport.

I'm now quite sure what you mean here (but let's worry about it later).

> I just want to avoid unnecessary trouble.

I'm pretty sure that this (modularizing mass transport) is *necessary* trouble. I'm going to do it anyway, so all I'm saying is that we should coordinate our efforts.

**Comment by ckhroulev** [comment] 2016-01-12 21:11
Before c0a7e56:

![wvelsurf-before](https://cloud.githubusercontent.com/assets/1018111/12276987/71558b24-b925-11e5-8a31-724de057f2ec.png)

After c0a7e56:

![wvelsurf-after](https://cloud.githubusercontent.com/assets/1018111/12276994/7d6c0802-b925-11e5-9f93-834b2c6f3bae.png)

**Closed by ckhroulev** 2016-01-12 21:11 UTC
Labels: bug

**Comment by bueler** [comment] 2016-01-12 21:19
Wow, nice!  And simple.
